modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="gpunoise"
version="1.0.0"
displayName="GPU Noise Acceleration"
updateJSONURL=""
displayURL=""
logoFile=""
credits=""
authors="Example"
description='''
Detects noise-based terrain generation and provides a GPU-acceleration hook for noise sampling.
'''

[[dependencies.gpunoise]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.gpunoise]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.gpunoise]]
modId="create"
mandatory=false
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.gpunoise]]
modId="valkyrienskies"
mandatory=false
versionRange="*"
ordering="NONE"
side="BOTH"
